### ISSUE TITLE
Using the/v1/chat/completion API, the end data "data: [DONE]" was not received

### ISSUE THREAD

**Issue by squallliu** [thxCode/llama-box#2]
method: POST
url: http://127.0.0.1:8080/v1/chat/completions
headers: [Accept: text/event-stream], [Authorization: Bearer e4nnF...XU]
body: {
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ],
  "temperature": 0.7,
  "stream": true
}

**Comment by thxCode** [comment]
@squallliu the ending event of `/v1/chat/completions` doesn't return `data:[DONE]`, but `/v1/completions` did.

**Comment by squallliu** [comment]
@thxCode see https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream

**Comment by thxCode** [comment]
it is fixed in HEAD. thanks.

**Comment by thxCode** [comment]
close as fixed
